server:
  port: 8080
  servlet:
    context-path: /users
spring:
  application:
    name: users
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bootvue?characterEncoding=UTF-8
    password: pass
    username: root
mybatis:
  mapper-locations: classpath:com/edu/mapper/*.xml
  type-aliases-package: com.edu.entity
